# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: LuxCore Python wheels

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  test_opencl:
    name: Test OpenCL capabilities on macos-14
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: install conda
        shell: bash
        run: |
          brew install miniconda
          conda --version
          conda update conda
          conda config --add channels conda-forge
          conda config --set channel_priority strict

      - name: install opencl deps
        shell: bash
        run: |
          brew install pocl
          conda install conda-forge::conda-libmamba-solver
          conda install conda-forge::pyopencl
          #conda install conda-forge::pocl
          conda install conda-forge::ocl_icd_wrapper_apple

      - name: install other deps
        shell: bash
        run: |
          pip install numpy
          pip install pyopencl

      - name: run script
        shell: bash
        run: |
          clinfo
          python ${{ github.workspace }}/main.py
